[build.environment]
  NODE_VERSION = "15.2.1"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--frozen-lockfile"
  BABEL_CACHE_FOLDER = "/opt/build/cache/"
  BUILD_REPORT_ERRORS_ONLY = "true"

[build]
  command = "yarn && yarn run build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
